services:
  turborepo-apps:
    image: turborepo-apps
    container_name: turborepo-apps
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    ports:
      - "3000:${APP_A_PORT}"
      - "3001:${APP_B_PORT}"
    env_file:
      - .env
    command: sleep infinity
    # command: /bin/sh -c "pnpm install && pnpm turbo dev"
