services:
  turborepo-apps:
    image: turborepo-apps
    container_name: turborepo-apps
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    environment:
      - WATCHPACK_POLLING=true
    command: sleep infinity
    # command: /bin/sh -c "pnpm install && pnpm turbo dev"
